// 인게임 로드아웃(장비구성) 화면의 스트라타젬 선택 격자 모델.
//
// 탭(카테고리) 순서와 각 탭 내부의 항목 순서는 게임 내 격자 배치와 일치해야 하며,
// 검증된 참조 데이터(ChubbyMaru/HD2-Helper의 database.json)의 배열 순서를
// 방향키 시퀀스(keys ↔ Sequence) 매칭으로 이 프로젝트 카탈로그(utils/stratagems.js)에
// 연결해 베이크한 것이다. (생성: .reference/derive-grid.mjs)
//
// 각 항목 i 는 (group=탭 index, row=floor(i/colCount), col=i%colCount) 위치를 가지며,
// 미보유(제외) 항목을 빼고 나면 실제 인게임 격자와 동일한 좌표가 된다.
//
// 임무(general) 타입은 로드아웃 격자에 없으므로 제외한다.

export const STRATAGEM_GRID_COLS = 4

// 탭 순서 = 인게임 스트라타젬 선택 화면의 카테고리 순서(공격, 보급, 방어)
export const STRATAGEM_GRID_TABS = ['attack', 'supply', 'defense']

// 각 배열 = 해당 카테고리 탭 내부의 인게임 순서 (stratagem.name 기준)
export const STRATAGEM_GRID = {
  attack: [
    'Orbital Precision Strike',
    'Orbital Gatling Barrage',
    'Orbital Airburst Strike',
    'Orbital Napalm Barrage',
    'Orbital 120MM HE Barrage',
    'Orbital Walking Barrage',
    'Orbital 380MM HE Barrage',
    'Orbital Railcannon Strike',
    'Orbital Laser',
    'Orbital EMS Strike',
    'Orbital Gas Strike',
    'Orbital Smoke Strike',
    'Eagle 500KG Bomb',
    'Eagle Strafing Run',
    'Eagle 110MM Rocket Pods',
    'Eagle Airstrike',
    'Eagle Cluster Bomb',
    'Eagle Napalm Airstrike',
    'Eagle Smoke Strike',
  ],
  supply: [
    'CQC-9 Defoliation Tool',
    'CQC-20 Breaching Hammer',
    'One True Flag',
    'Machine Gun',
    'Stalwart',
    'Heavy Machine Gun',
    'Railgun',
    'Speargun',
    'Anti-Materiel Rifle',
    'Epoch',
    'Grenade Launcher',
    'GL-52 De-Escalator',
    'Sterilizer',
    'Flamethrower',
    'Laser Cannon',
    'Quasar Cannon',
    'Arc Thrower',
    'Commando',
    'EAT-411 Leveller',
    'Expendable Napalm',
    'Solo Silo',
    'MGX-42 Bullet Storm',
    'Expendable Anti-Tank',
    'Autocannon',
    'Airburst Rocket Launcher',
    'Spear',
    'B/FLAM-80 Cremator',
    'W.A.S.P. Launcher',
    'M-1000 Maxigun',
    'GL-28 Belt-Fed Grenade Launcher',
    'Recoilless Rifle',
    'B/MD C4 Pack',
    'Supply Pack',
    'Portable Hellbomb',
    'Warp Pack',
    'Hover Pack',
    'Jump Pack',
    'Shield Generator Pack',
    'Directional Shield',
    'Ballistic Shield Backpack',
    '“Guard Dog” K-9',
    'AX/FLAM-75 Hot Dog',
    '“Guard Dog”',
    '“Guard Dog” Rover',
    '"Guard Dog" Dog Breath',
    'TD-220 Bastion MK XVI',
    'Fast Recon Vehicle',
    'Emancipator Exosuit',
    'Patriot Exosuit',
    'EXO-55 Breakthrough Exosuit',
    'EXO-51 Lumberer Exosuit',
  ],
  defense: [
    'Gatling Sentry',
    'Machine Gun Sentry',
    'Flame Sentry',
    'Laser Sentry',
    'Rocket Sentry',
    'Autocannon Sentry',
    'EMS Mortar Sentry',
    'A/GM-17 Gas Mortar Sentry',
    'Mortar Sentry',
    'Shield Generator Relay',
    'Grenadier Battlement',
    'Anti-Tank Emplacement',
    'HMG Emplacement',
    'Tesla Tower',
    'Anti-Tank Mines',
    'Gas Mines',
    'Anti-Personnel Minefield',
    'Incendiary Mines',
  ],
}
